courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
  url(r'^$', views.course_list),
  url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/$', views.step_detail),
  url(r'(?P<pk>\d+)/$', views.course_detail),
]

interview_assessment/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from . import view
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # The first argument is an empty string, so any request that doesn't match anything go to the hello world view
    url(r'^courses/', include('courses.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', view.hello_world),
]

 # Check if we're in dev and then check if we have a static path and include them
urlpatterns += staticfiles_urlpatterns()

courses/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Course(models.Model):
  created_at = models.DateTimeField(auto_now_add=True)
  title = models.CharField(max_length=255)
  description = models.TextField()

  def __str__(self):
    return self.title


class Step(models.Model):
  title = models.CharField(max_length=255)
  description = models.TextField()
  content = models.TextField(blank=True, default='')
  order = models.IntegerField(default=0)
  course = models.ForeignKey(Course)

  class Meta:
    ordering = ['order',]

  def __str__(self):
    return self.title

courses/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404

from .models import Course, Step

def course_list(request):
  courses = Course.objects.all()
  return render(request, 'courses/course_list.html', {'courses': courses})

def course_detail(request, pk):
  course = get_object_or_404(Course, pk=pk)
  return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
  step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
  return render(request, 'courses/step_detail.html', {'step': step})

def article_detail(request, pk):
  step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)

courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %} {{ course.title }} {% endblock %}

{% block content %}
  <article>
    <h2>{{ course.title }}</h2>
    {{ course.description }}

    <section>
      {% for step in course.step_set.all %}
        <h3>{{ step.title }}</h3>
        {{ step.description}}
      {% endfor %}
    </section>
  </article>
{% endblock %}

courses/templates/courses/course_list.html
{% for course in courses %}
<h2>{{ course.title }}</h2>
{{ course.description}}
{% endfor %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% block title %} {{ step.title }} - {{ step.course.title }} {% endblock %}

{% block content %}

<article>
  <h2> {{ step.course.title }} </h2>
  <h3>{{step.title}}</h3>
  {{ step.content|linebreaks }}
</article>

{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block title %} well hello there {% endblock %}

{% block content %}
  <h1>welcome to home</h1>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!doctype html>
<html>
  <head>
    <title>{% block title %} hi {% endblock %} </title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
  </head>
  <body>
    <div class="site-container">
      {% block content %} {% endblock %}
    </div>
  </body>
</html>